/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import javax.swing.*;



public class Main {
    public static void main(String[] args) {

        Login user = new Login();

        user.firstName = JOptionPane.showInputDialog("Enter Your Your First Name");

        user.lastName = JOptionPane.showInputDialog("Enter Your Your First Name");

        // ENTER USERNAME
        do{
            user.username = JOptionPane.showInputDialog("Enter Username: Username should be \n no more  than 5" +
                    " characters and\n contain an underscore(_) ");
            user.isValidUser = user.checkUserName(user.username);
            if(!user.isValidUser){
                JOptionPane.showMessageDialog(null,"Username is not correctly formatted, please ensure \n that your username contains an underscore\n  an is more than 5 characters in length");
            }else{
                JOptionPane.showMessageDialog(null,"Username successfully captured");
            }
        }while(!user.isValidUser);

        // ENTER PASSWORD
        do{
            user.password = JOptionPane.showInputDialog("""
                    Enter Password: Your Password Should More Than\s
                     8 Characters Long, Contain A Capital
                     Letter,Contain A Number,
                     And Also Contain A Special Character""");
            user.isValidPassword = user.checkPasswordComplexity(user.password);
            if(!user.isValidPassword){
                String message = "Password is not correctly formatted, please ensure that your password contains  at least 8 " +
                        " characters, a capital letter, a number and a special character";
                JOptionPane.showMessageDialog(null,message);
            }else{
                JOptionPane.showMessageDialog(null,"Password successfully captured");
            }
        }while(!user.isValidPassword);

        JOptionPane.showMessageDialog(null,user.registerUser(user.username,user.password));
//         USER LOG IN
        JOptionPane.showMessageDialog(null,"You Can Now Login Using The Same Credentials");

        do{
            String loginUsername = JOptionPane.showInputDialog("Login:\n USERNAME Credentials");
            String loginPassword = JOptionPane.showInputDialog("Login:\n PASSWORD Credentials");
            user.isLoginIn =  user.loginUser(loginUsername,loginPassword,user.username,user.password);
            if(!user.isLoginIn){
                JOptionPane.showMessageDialog(null,"Your login details do not match try again");
            }

        }while(!user.isLoginIn);

        user.returnLoginStatus(user.isLoginIn, user.firstName, user.lastName);

        JOptionPane.showMessageDialog(null,"Welcome to EasyKanban");
    }
}